name: 'Blender Action'
description: 'GitHub Action to automate Blender tasks such as STL export and PNG render'

inputs:
  input_file:
    description: 'Blender source file'
    required: true

  output_file:
    description: 'Path to export STL file'
    required: true

  thumbnail_file:
    description: 'Path to thumbnail preview file of the STL'
    required: false

  export_selected:
    description: 'Whether to export only selected objects (true/false)'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'zap'
  color: 'gray-dark'
